spring:
  application:
    name: newstock
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      mode: always

jwt:
  secret-key: ${SECRET_KEY}
  refresh-key: ${REFRESH_KEY}
