spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria-1.clwm8q0y4es7.ap-northeast-2.rds.amazonaws.com:3306/ssafy
    username: ${DEV_NAME}
    password: ${DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
