spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/newstock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_NAME}
    password: ${LOCAL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true
  data:
    redis:
      host: localhost
      port: 6379
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8080
  address: localhost

serverName: local_server
