spring:
  config:
    activate:
      on-profile: green
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria-1.clwm8q0y4es7.ap-northeast-2.rds.amazonaws.com:3306/ssafy
    username: ${DEV_NAME}
    password: ${DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: false  # Flyway 비활성화

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: ${REDIS_PASSWORD}



server:
  port: 8081
  address: 0.0.0.0

serverName: green_server